theme: jekyll-theme-minimal
repository: nineties/aboutme

title: About Me
logo: https://community.arm.com/resized-image/__size/320x240/__key/communityserver-blogs-components-weblogfiles/00-00-00-37-93/Koichi.jpg

github:
    - project_tagline: test
    - is_user_page: true
    - is_project_page: false

google_analytics: UA-129434657-1
